import streamlit as st
import os

st.set_page_config(page_title="Live Markdown Preview", page_icon="📝", layout="wide")

st.title("📝 Live Markdown Preview")
st.markdown("Test out your generated GitCanvas components and build your profile README in real-time.")

# Default demo text
DEMO_MARKDOWN = """# Hi there, I'm a GitCanvas User 👋

Welcome to my GitHub profile! Here are some of my stats generated by GitCanvas:

![Stats](https://gitcanvas-api.vercel.app/api/stats?username=torvalds&theme=dark)

## My Top Languages
![Languages](https://gitcanvas-api.vercel.app/api/languages?username=torvalds&theme=dark)

---
*Feel free to replace this with your own Markdown code copied from the GitCanvas generators.*
"""

# Initialize session state for the markdown input
if "md_text" not in st.session_state:
    st.session_state.md_text = DEMO_MARKDOWN

col1, col2 = st.columns(2)

with col1:
    st.subheader("Markdown Source")
    st.caption("Type or paste your Markdown here. The preview will update automatically.")
    
    # Text area for markdown input
    md_input = st.text_area(
        "Source Code",
        value=st.session_state.md_text,
        height=500,
        label_visibility="collapsed",
        key="md_input_area"
    )
    
    # Update session state if it changed
    if md_input != st.session_state.md_text:
        st.session_state.md_text = md_input
        # We don't need to rerun explicitly because text_area triggers a rerun when focus is lost
        
    c1, c2, c3 = st.columns([1, 1, 2])
    if c1.button("🔄 Reset Demo", use_container_width=True):
        st.session_state.md_text = DEMO_MARKDOWN
        st.rerun()
        
    if c2.button("🗑️ Clear", use_container_width=True):
        st.session_state.md_text = ""
        st.rerun()
        
    st.markdown("💡 **Tip:** Copy the Markdown snippets from the GitCanvas tabs and paste them here to see how they look together!")

with col2:
    st.subheader("Live Preview")
    st.caption("How it will appear on GitHub")
    
    # Render the markdown inside a styled container to look like GitHub
    st.markdown(
        \"\"\"
        <style>
        .github-preview {
            background-color: #0d1117;
            border: 1px solid #30363d;
            border-radius: 6px;
            padding: 24px;
            min-height: 500px;
        }
        .github-preview img {
            max-width: 100%;
        }
        </style>
        \"\"\",
        unsafe_allow_html=True
    )
    
    st.markdown('<div class="github-preview">', unsafe_allow_html=True)
    if st.session_state.md_text.strip():
        st.markdown(st.session_state.md_text, unsafe_allow_html=True)
    else:
        st.info("Nothing to preview. Start typing on the left!")
    st.markdown('</div>', unsafe_allow_html=True)

# Navigation back
st.markdown("---")
st.page_link("app.py", label="🔙 Back to Profile Architect", icon="⬅️")
